### ISSUE TITLE
Syntax highlighting is removed

### ISSUE THREAD

**Issue by ghost** [amalrajan/www.learncpp.com-Crawler#46]
In the website where it sometimes shows snippets of code you can see the code syntax
![image](https://github.com/amalrajan/learncpp-download/assets/70875007/9873a953-b84e-4ade-bceb-5d0b776ac5c0)

However, in the PDFs, this syntax highlighting is removed
![image](https://github.com/amalrajan/learncpp-download/assets/70875007/ee54d910-14a8-4c5f-93b3-2cb29ed58dc3)

**Comment by amalrajan** [comment]
Fixed, closing. Thanks for reporting!
